---
title: Sett sprite rotasjon stil
hero_image: images / banner.png
description: Sett rotasjonsstilen til et sprite
theme: rød
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: skaperen, design-0, programmering-0, phys-comp-0, produksjon-0, fellesskap-0
interests: ""
technologies: "ripe"
site_areas:
steps:
  - 
    title: Introduksjon
