---
title: Legen Sie den Sprite-Rotationsstil fest
hero_image: Bilder / Banner.png
description: Legen Sie den Rotationsstil eines Sprites fest
theme: rot
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: Schöpfer, Design-0, Programmierung-0, Phys-Comp-0, Herstellung-0, Community-0
interests: ""
technologies: "kratzen"
site_areas: ""
steps:
  - 
    title: Einführung
