---
title: スプライトの回転スタイルを設定する
hero_image: images / banner.png
description: スプライトの回転スタイルを設定する
theme: 赤
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: クリエイター、デザイン-0、プログラミング-0、phys-comp-0、製造-0、コミュニティ-0
interests: ""
technologies: "スクラッチ"
site_areas: ""
steps:
  - 
    title: 前書き
