---
title: Đặt kiểu quay sprite
hero_image: images / banner.png
description: Đặt kiểu quay của một sprite
theme: đỏ
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: tác giả, thiết kế-0, lập trình-0, phys-comp-0, sản xuất-0, cộng đồng-0
interests: ""
technologies: "vết trầy"
site_areas:
steps:
  - 
    title: Giới thiệu
