---
title: Imposta lo stile di rotazione dello sprite
hero_image: images / banner.png
description: Imposta lo stile di rotazione di uno sprite
theme: rosso
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: creatore, design-0, programmazione-0, compatta-0, fabbricazione-0, comunità-0
interests: ""
technologies: "graffiare"
site_areas: ""
steps:
  - 
    title: introduzione
