---
title: Indstil sprite rotation stil
hero_image: images / banner.png
description: Indstil rotationsstilen for et sprite
theme: rød
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: skaber, design-0, programmering-0, phys-comp-0, fremstilling-0, community-0
interests: ""
technologies: "kradse"
site_areas:
steps:
  - 
    title: Introduktion
