---
title: Definir estilo de rotação do sprite
hero_image: images / banner.png
description: Defina o estilo de rotação de um sprite
theme: vermelho
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: criador, design-0, programação-0, computação-física-0, fabrico-0, comunidade-0
interests: ""
technologies: "scratch"
site_areas:
steps:
  - 
    title: Introdução
