---
title: Aseta hahmon pyöritystyyli
hero_image: images/banner.png
description: Aseta hahmon pyöritystyyli
theme: punainen
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: ""
technologies: "scratch"
site_areas:
steps:
  - 
    title: Esittely
