---
title: Dewis steil troi'r ciplun
hero_image: images/banner.png
description: Dewisiwch steil troi ciplun
theme: coch
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: crewr, dylunio-0, rhaglennu-0, cyfrifiadureg-corfforol-0, gweithgynhyrchu-0, cymmuned-0
interests: ""
technologies: "scratch"
site_areas:
steps:
  - 
    title: Cyflwyniad
