---
title: Establecer el estilo de rotación de sprites
hero_image: images / banner.png
description: Establecer el estilo de rotación de un sprite
theme: rojo
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: creador, diseño-0, programación-0, phys-comp-0, fabricación-0, comunidad-0
interests: ""
technologies: "rasguño"
site_areas: ""
steps:
  - 
    title: Introducción
