---
title: Lege den Drehmodus für die Figur fest
hero_image: images/banner.png
description: Legen Sie den Rotationsstil eines Sprites fest
theme: rot
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: Schöpfer, Design-0, Programmierung-0, Phys-Comp-0, Herstellung-0, Community-0
interests: ""
technologies: "kratzen"
site_areas:
steps:
  - 
    title: Einführung
