---
title: Setați modul de rotire al personajului
hero_image: images/banner.png
description: Setați modul de rotire al unui personaj
theme: red
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: creator, design-0, programare-0, fiz-comp-0, fabricare-0, comunitate-0
interests: ""
technologies: "scratch"
site_areas:
steps:
  - title: Introducere
