---
title: Définir le style de rotation du sprite
hero_image: images / banner.png
description: Définir le style de rotation d'un sprite
theme: rouge
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: créateur, design-0, programmation-0, phys-comp-0, fabrication-0, communauté-0
interests: ""
technologies: "rayure"
site_areas: ""
steps:
  - 
    title: introduction
