---
title: Nastavte štýl striedania sprite
hero_image: images / banner.png
description: Nastavte štýl otáčania sprite
theme: červená
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: tvorca, dizajn-0, programovanie-0, phys-comp-0, výroba-0, komunita-0
interests: ""
technologies: "škrabanec"
site_areas: ""
steps:
  - 
    title: úvod
