---
title: Ställ in spritrotationsstil
hero_image: images / banner.png
description: Ställ rotationsstilen för en sprite
theme: röd
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: skapare, design-0, programmering-0, phys-comp-0, tillverkning-0, community-0
interests: ""
technologies: "repa"
site_areas:
steps:
  - 
    title: Introduktion
